<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Recibo Online</title>

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<!--<link rel="stylesheet" type="text/css" href="/css/style.css">-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>
		<script>
			$(document).ready(function () { 
				var options = {
    			onKeyPress: function (cpf, ev, el, op) {
        		var masks = ['000.000.000-000', '00.000.000/0000-00'];
        		$('.CPF_CNPJ').mask((cpf.length > 14) ? masks[1] : masks[0], op);
    			}
				}
				$('.cpfOuCnpj').length > 11 ? $('.CPF_CNPJ').mask('00.000.000/0000-00', options) : $('.CPF_CNPJ').mask('000.000.000-00#', options);
			});
		</script>
		<script>
			$(document).ready(function () { 
				var $seuCampoTel = $("#PHONE");
				$seuCampoTel.mask('(00) 00000-0000', {reverse: false});
			});
		</script>
		<script>
			$(document).ready(function () { 
				var $seuCampoDate = $("#DATE");
				$seuCampoDate.mask('00/00/0000', {reverse: false});
			});
		</script>
		<script>
			$(document).ready(function () { 
				$('#VALOR').mask('000.000.000.000.000,00', {reverse: true});
			});
		</script>

	</head>
	<body>
		<?= $this->content() ?>
	</body>
</html>